### ISSUE TITLE
Aqua Patcher not working for me

### ISSUE THREAD

**Issue by plxjammerplx** [AkiraJkr/Birth-by-Sleep-HD-ReMix#10]
I have followed instructions from the notepad file in the patcher folder, everything else from hd textures to japanese audio is working properly for me. I keep getting a "xdelta3: target window checksum mismatch: XD3_INVALID_INPUT" error message.

I'm also using the correct english patched iso.

**Comment by AkiraJkr** [comment]
That's an issue with xdelta...unless someone makes a new patch with her model, doing the exact same thing I did to her textures, and makes it for each iso and version of the game out there...you're stuck not being able to patch her 2.5 model until you get the 'correct' iso. 

And I cannot provide any downloads, nor know of any that are absolute to work.
